### ISSUE TITLE
Fatal Exception java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by gmorales** [criteo/android-publisher-sdk#228]
There are some OOM errors for some users using the latest version available (4.4.0). Here is the stack trace.

````java
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 842083648 byte allocation with 1415026 free bytes and 507MB until OOM, max allowed footprint 5660106, growth limit 536870912
       at com.squareup.tape.QueueFile.peek(QueueFile.java:414)
       at com.squareup.tape.FileObjectQueue.peek(FileObjectQueue.java:55)
       at com.criteo.publisher.e0.z.a(z.java:80)
       at com.criteo.publisher.e0.z.a(z.java:63)
       at com.criteo.publisher.e0.e0.b(e0.java:193)
       at com.criteo.publisher.e0.e0.a(e0.java:151)
       at com.criteo.publisher.e0.j.a(j.java:63)
       at com.criteo.publisher.e0.j.a(j.java:46)
       at com.criteo.publisher.logging.l$a.a(l.java:29)
       at com.criteo.publisher.logging.l$a.a(l.java:26)
       at com.criteo.publisher.logging.j.a(j.java:52)
       at com.criteo.publisher.logging.g.a(g.java:112)
       at com.criteo.publisher.m0.o.a(o.java:32)
       at com.criteo.publisher.h0.c.c(c.java:60)
       at com.criteo.publisher.h0.c.b(c.java:38)
       at com.criteo.publisher.logging.k.a(k.java:74)
       at com.criteo.publisher.logging.j.a(j.java:43)
       at com.criteo.publisher.logging.g.a(g.java:112)
       at com.criteo.publisher.w.run(w.java:63)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
````

**Comment by TurpIF** [comment]
Hi,

Thank you for reporting this. The OOM is thrown when we're verifying the validity of a queue file. In this case, having an single element in the queue of 800MB is clearly a corruption.
I've added a catch of the OOM on this check in #230, so this issue should not be visible anymore.

The fix should be available in the next version: 4.5.0.

By curiosity, do you have a deterministic way to reproduce this error ?

**Comment by gmorales** [comment]
Thank you for the quick response @TurpIF! About a deterministic way to
reproduce this error, sadly no. There are small bunch of users that
experiment the crashes because I get the logs from Firebase
Crashlytics. One thing is that this occurs in the production build.

[image: Screenshot 2021-08-24 at 21.03.47.png][image: Screenshot 2021-08-24
at 21.02.03.png]
