### ISSUE TITLE
WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by kunalkhedkar** [criteo/android-publisher-sdk#257]
Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:445)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:262)
       at android.webkit.WebView.getFactory(WebView.java:2576)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
       at android.view.View.<init>(View.java:5360)
       at android.view.View.<init>(View.java:5512)
       at android.view.ViewGroup.<init>(ViewGroup.java:699)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
       at android.webkit.WebView.<init>(WebView.java:413)
       at android.webkit.WebView.<init>(WebView.java:355)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:324)
       at android.webkit.WebView.<init>(WebView.java:314)
       at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:127)
       at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:118)
       at com.xxx.CmCriteoPartnerAdapter$1.onResponse(CmCriteoPartnerAdapter.java:69)
       at com.criteo.publisher.j$a.a(j.java:81)
       at androidx.browser.trusted.TrustedWebActivityServiceConnectionPool$$InternalSyntheticLambda$0$f29f88fc32e33fae3211417ede76c925f1a10ee2b24ccea20bf8a969a28a5f3c$0.run$bridge(TrustedWebActivityServiceConnectionPool.java:32)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       
       =====================================================================
       Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:349)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:412)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:262)
       at android.webkit.WebView.getFactory(WebView.java:2576)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
       at android.view.View.<init>(View.java:5360)
       at android.view.View.<init>(View.java:5512)
       at android.view.ViewGroup.<init>(ViewGroup.java:699)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
       at android.webkit.WebView.<init>(WebView.java:413)
       at android.webkit.WebView.<init>(WebView.java:355)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:324)
       at android.webkit.WebView.<init>(WebView.java:314)
       at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:127)
       at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:118)
       at com.xxx.CmCriteoPartnerAdapter$1.onResponse(CmCriteoPartnerAdapter.java:69)
       at com.criteo.publisher.j$a.a(j.java:81)
       at androidx.browser.trusted.TrustedWebActivityServiceConnectionPool$$InternalSyntheticLambda$0$f29f88fc32e33fae3211417ede76c925f1a10ee2b24ccea20bf8a969a28a5f3c$0.run$bridge(TrustedWebActivityServiceConnectionPool.java:32)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       
       ============================================================
       
       Background:
       I am using 'com.criteo.publisher:criteo-publisher-sdk:4.6.0' sdk on Android app
       
       Crash stats:
       Last 90 days (2022-06-03) -> 997 crash events affecting 149 users
       
       Device
       35% samsung (LGE, sky device, SKY, 7% motorola, 6% TCL, 3% BLU, 3% Google, 2% TINNO, 1% HMD Global,<1% HTC, <1% 
       OnePlus)

       Android OS:
       60% on Android11 (Android 5,6,8,9,10,11,12)

**Comment by TurpIF** [comment]
Hi @kunalkhedkar ,

Thank you for reporting such issue. Do you know how to reproduce such error ?
Do you have more information on the crash stats ? Like there is 149 affected users on how many ?

Regards,
Pierre

**Comment by kunalkhedkar** [comment]
Hi @TurpIF 
Thank you for the quick response.

Sorry! I don't have steps to reproduce this crash. Adding crash info from firebase crashlytics.
We have large user base, over 1 million+ users, out of 997 crash events affecting 149 users
Adding some device names (Galaxy A12, Galaxy A01, Galaxy A03s)

If you need any other information, please let me know.
Thanks

**Comment by smizan-wesson** [comment]
> Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
>        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:445)
>        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:262)
>        at android.webkit.WebView.getFactory(WebView.java:2576)
>        at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
>        at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
>        at android.view.View.<init>(View.java:5360)
>        at android.view.View.<init>(View.java:5512)
>        at android.view.ViewGroup.<init>(ViewGroup.java:699)
>        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
>        at android.webkit.WebView.<init>(WebView.java:413)
>        at android.webkit.WebView.<init>(WebView.java:355)
>        at android.webkit.WebView.<init>(WebView.java:337)
>        at android.webkit.WebView.<init>(WebView.java:324)
>        at android.webkit.WebView.<init>(WebView.java:314)
>        at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:127)
>        at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:118)
>        at com.xxx.CmCriteoPartnerAdapter$1.onResponse(CmCriteoPartnerAdapter.java:69)
>        at com.criteo.publisher.j$a.a(j.java:81)
>        at androidx.browser.trusted.TrustedWebActivityServiceConnectionPool$$InternalSyntheticLambda$0$f29f88fc32e33fae3211417ede76c925f1a10ee2b24ccea20bf8a969a28a5f3c$0.run$bridge(TrustedWebActivityServiceConnectionPool.java:32)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:223)
>        at android.app.ActivityThread.main(ActivityThread.java:7986)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
>        
>        =====================================================================
>        Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
>        at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:349)
>        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:412)
>        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:262)
>        at android.webkit.WebView.getFactory(WebView.java:2576)
>        at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
>        at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
>        at android.view.View.<init>(View.java:5360)
>        at android.view.View.<init>(View.java:5512)
>        at android.view.ViewGroup.<init>(ViewGroup.java:699)
>        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
>        at android.webkit.WebView.<init>(WebView.java:413)
>        at android.webkit.WebView.<init>(WebView.java:355)
>        at android.webkit.WebView.<init>(WebView.java:337)
>        at android.webkit.WebView.<init>(WebView.java:324)
>        at android.webkit.WebView.<init>(WebView.java:314)
>        at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:127)
>        at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:118)
>        at com.xxx.CmCriteoPartnerAdapter$1.onResponse(CmCriteoPartnerAdapter.java:69)
>        at com.criteo.publisher.j$a.a(j.java:81)
>        at androidx.browser.trusted.TrustedWebActivityServiceConnectionPool$$InternalSyntheticLambda$0$f29f88fc32e33fae3211417ede76c925f1a10ee2b24ccea20bf8a969a28a5f3c$0.run$bridge(TrustedWebActivityServiceConnectionPool.java:32)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:223)
>        at android.app.ActivityThread.main(ActivityThread.java:7986)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
>        
>        ============================================================
>        
>        Background:
>        I am using 'com.criteo.publisher:criteo-publisher-sdk:4.6.0' sdk on Android app
>        
>        Crash stats:
>        Last 90 days (2022-06-03) -> 997 crash events affecting 149 users
>        
>        Device
>        35% samsung (LGE, sky device, SKY, 7% motorola, 6% TCL, 3% BLU, 3% Google, 2% TINNO, 1% HMD Global,<1% HTC, <1% 
>        OnePlus)
> 
>        Android OS:
>        60% on Android11 (Android 5,6,8,9,10,11,12)
> 
>        
>
